<a href="https://colab.research.google.com/github/Vishal-113/RNN-and-NLP/blob/main/Scaled_Dot_Product_Attention_and_Q%26A_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def scaled_dot_product_attention(Q, K, V):
    # Step 1: Dot product of Q and K transpose
    matmul_qk = np.matmul(Q, K.T)

    # Step 2: Scale by sqrt(d)
    d_k = K.shape[-1]
    scaled_attention_logits = matmul_qk / np.sqrt(d_k)

    # Step 3: Softmax to get attention weights
    attention_weights = np.exp(scaled_attention_logits)
    attention_weights /= np.sum(attention_weights, axis=-1, keepdims=True)

    # Step 4: Multiply weights with V
    output = np.matmul(attention_weights, V)

    return output, attention_weights

# Test inputs
Q = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

output, attention_weights = scaled_dot_product_attention(Q, K, V)

print("Attention Weights:\n", attention_weights)
print("\nOutput:\n", output)

Attention Weights:
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]

Output:
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]


1. Why do we divide the attention score by √d in scaled dot-product attention?
Ans: It’s a normalization trick to keep the attention stable.
     When computing attention scores (i.e., Q · Kᵀ), the result can become very large, especially when the dimension d of the vectors is high.
	1.Large dot products → very large numbers going into the softmax.
	2.That makes softmax outputs very sharp — meaning one word gets almost all the attention, and others get nearly zero.
	3.This hurts learning by making gradients too small to adjust during training (a problem called vanishing gradients).
     *Dividing by √d keeps the values in a reasonable range, leading to:
	1.Smoother softmax outputs
	2.More stable gradients
	3.Better learning overall


2. How does self-attention help the model understand relationships between words in a sentence?
Ans: Self-attention allows every word in a sentence to look at (or "attend to") every other word, including itself. This helps the model understand context and relationships.
     For example, in the sentence:
	“The cat sat on the mat because it was tired.”
     When processing "it", self-attention allows the model to look back at "cat" to understand what "it" refers to.
     When processing "mat", the model can focus on "sat" or "on" to better understand the spatial meaning.

     Self-attention captures context by dynamically weighting which words are important for understanding each word's meaning — regardless of position.